# Generated by Django 2.2.3 on 2019-11-04 18:55

from django.db import migrations
import pandas as pd
import numpy as np

class Migration(migrations.Migration):

    def import_sample_dataset(apps, schema_editor):
        Metric = apps.get_model('metrics', 'Metric')
        sample_dataset_df = pd.read_csv("dataset.csv")
        sample_dataset_df['date'] = sample_dataset_df['date'].astype('datetime64[ns]')
        sample_dataset_df['spend'] = sample_dataset_df['spend'].astype(float)
        sample_dataset_df['revenue'] = sample_dataset_df['revenue'].astype(float)
        #sample_dataset_df['cpi'] = np.round(sample_dataset_df['spend']/sample_dataset_df['installs'],2)

        def save_metric(metric):
            metric = Metric(**dict(metric))
            metric.save()

        sample_dataset_df.apply(save_metric, axis=1)

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(import_sample_dataset)
    ]
